<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>caddy_ai2_ros2_control_system_bicycle_controller</name>
  <version>0.1.0</version>
  <description>ROS2 to chain the traction and steering controller to bicycle controller for Caddy AI2</description>
  <maintainer email="racarla1@inf.upv.es">Rafael Carbonell Lázaro</maintainer>
  <license>CC-BY-4.0</license>

  <!-- Dependencias requeridas -->
  <depend>rclcpp</depend>
  <depend>controller_manager</depend>
  <depend>hardware_interface</depend>
  <depend>joint_state_broadcaster</depend>
  <depend>ros2_control</depend>

  <!-- Paquetes de controladores -->
  <depend>caddy_ai2_ros2_control_system_steering_driver</depend>
  <depend>caddy_ai2_ros2_control_system_traction_driver</depend>
  <depend>caddy_ai2_ros2_common</depend>

  <!-- Para spawner y launch -->
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
      <build_type>ament_cmake</build_type>
  </export>
</package>