controller_manager:
  ros__parameters:
    update_rate: 100

bicycle_steering_controller:
  ros__parameters:
    type: bicycle_steering_controller/BicycleSteeringController

    traction_joints_names: ['system_traction_joint']
    steering_joints_names: ['system_steering_joint']
    wheelbase: 0.325
    traction_wheel_radius: 0.235

    reference_timeout: 2.0

    open_loop: true
    position_feedback: false
    velocity_rolling_window_size: 10
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: false
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]